package com.example.autoservice.inject;

import com.example.autoservice.model.Car;
import com.example.autoservice.model.CarOwner;
import com.example.autoservice.model.Mechanic;
import com.example.autoservice.model.Order;
import com.example.autoservice.model.Product;
import com.example.autoservice.model.Service;
import com.example.autoservice.service.CarOwnerService;
import com.example.autoservice.service.CarService;
import com.example.autoservice.service.MechanicService;
import com.example.autoservice.service.OrderService;
import com.example.autoservice.service.ProductService;
import com.example.autoservice.service.ServiceService;
import jakarta.annotation.PostConstruct;
import java.math.BigDecimal;
import java.util.List;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Component;

@Component
@AllArgsConstructor
public class InjectController {
    private final CarService carService;
    private final ProductService productService;
    private final MechanicService mechanicService;
    private final CarOwnerService carOwnerService;
    private final OrderService orderService;
    private final ServiceService serviceService;

    @PostConstruct
    void injectTestData() {
        Car car1 = new Car();
        car1.setManufacturer("Toyota");
        car1.setModel("Corolla");
        car1.setYear(2020);
        car1.setNumber("ABC123");
        Car car2 = new Car();
        car2.setManufacturer("Honda");
        car2.setModel("Civic");
        car2.setYear(2018);
        car2.setNumber("XYZ789");
        Car car3 = new Car();
        car3.setManufacturer("Ford");
        car3.setModel("Mustang");
        car3.setYear(2015);
        car3.setNumber("DEF456");
        Car car4 = new Car();
        car4.setManufacturer("Chevrolet");
        car4.setModel("Camaro");
        car4.setYear(2019);
        car4.setNumber("GHI789");
        Car car5 = new Car();
        car5.setManufacturer("Nissan");
        car5.setModel("Sentra");
        car5.setYear(2022);
        car5.setNumber("JKL101");
        Car car6 = new Car();
        car6.setManufacturer("BMW");
        car6.setModel("X5");
        car6.setYear(2021);
        car6.setNumber("MNO222");
        Car car7 = new Car();
        car7.setManufacturer("Ford");
        car7.setModel("Mustang");
        car7.setYear(2022);
        car7.setNumber("PQR333");
        Car car8 = new Car();
        car8.setManufacturer("Toyota");
        car8.setModel("Corolla");
        car8.setYear(2020);
        car8.setNumber("XYZ444");
        Car car9 = new Car();
        car9.setManufacturer("Chevrolet");
        car9.setModel("Camaro");
        car9.setYear(2021);
        car9.setNumber("ABC555");
        Car car10 = new Car();
        car10.setManufacturer("Honda");
        car10.setModel("Civic");
        car10.setYear(2019);
        car10.setNumber("DEF666");
        Car car11 = new Car();
        car11.setManufacturer("Tesla");
        car11.setModel("Model 3");
        car11.setYear(2023);
        car11.setNumber("GHI777");
        List.of(car1, car2, car3, car4, car5, car6, car7,car8, car9, car10, car11)
                .forEach(carService::add);

        Product product1 = new Product();
        product1.setName("Engine Oil");
        product1.setPrice(new BigDecimal("30.00"));
        Product product2 = new Product();
        product2.setName("Air Filter");
        product2.setPrice(new BigDecimal("12.50"));
        Product product3 = new Product();
        product3.setName("Brake Pads");
        product3.setPrice(new BigDecimal("45.99"));
        Product product4 = new Product();
        product4.setName("Spark Plugs");
        product4.setPrice(new BigDecimal("8.99"));
        Product product5 = new Product();
        product5.setName("Tire Pressure Gauge");
        product5.setPrice(new BigDecimal("19.99"));
        Product product6 = new Product();
        product6.setName("Transmission Fluid");
        product6.setPrice(new BigDecimal("24.99"));
        Product product7 = new Product();
        product7.setName("Brake Pads");
        product7.setPrice(new BigDecimal("49.99"));
        Product product8 = new Product();
        product8.setName("Engine Oil");
        product8.setPrice(new BigDecimal("29.99"));
        Product product9 = new Product();
        product9.setName("Air Filter");
        product9.setPrice(new BigDecimal("12.99"));
        Product product10 = new Product();
        product10.setName("Spark Plugs");
        product10.setPrice(new BigDecimal("6.99"));
        Product product11 = new Product();
        product11.setName("Tire Pressure Gauge");
        product11.setPrice(new BigDecimal("8.99"));
        List.of(product1, product2, product3, product4, product5,
                        product6, product7, product8, product9, product10, product11)
                .forEach(productService::add);

        Mechanic mechanic1 = new Mechanic();
        mechanic1.setFullName("Antony");
        Mechanic mechanic2 = new Mechanic();
        mechanic2.setFullName("Barbara");
        Mechanic mechanic3 = new Mechanic();
        mechanic3.setFullName("Charlie");
        Mechanic mechanic4 = new Mechanic();
        mechanic4.setFullName("Diana");
        Mechanic mechanic5 = new Mechanic();
        mechanic5.setFullName("Edward");
        Mechanic mechanic6 = new Mechanic();
        mechanic6.setFullName("Fiona");
        List.of(mechanic1, mechanic2, mechanic3, mechanic4, mechanic5, mechanic6)
                .forEach(mechanicService::add);

        CarOwner carOwner1 = new CarOwner();
        carOwner1.setFullName("Bob");
        List.of(car1, car2, car3).forEach(carOwner1::addCar);
        CarOwner carOwner2 = new CarOwner();
        carOwner2.setFullName("Alice");
        List.of(car4, car5, car6).forEach(carOwner2::addCar);
        CarOwner carOwner3 = new CarOwner();
        carOwner3.setFullName("John");
        List.of(car7, car8, car9).forEach(carOwner3::addCar);
        List.of(carOwner1, carOwner2, carOwner3).forEach(carOwnerService::add);

        Service service2 = new Service();
        service2.setName("Oil Change");
        service2.setMechanic(mechanic6);
        service2.setPrice(new BigDecimal("85.75"));
        service2.setWasPaidToMechanic(false);
        Service service3 = new Service();
        service3.setName("Brake Inspection");
        service3.setMechanic(mechanic1);
        service3.setPrice(new BigDecimal("100.00"));
        service3.setWasPaidToMechanic(false);
        Service service4 = new Service();
        service4.setName("Transmission Service");
        service4.setMechanic(mechanic2);
        service4.setPrice(new BigDecimal("75.50"));
        service4.setWasPaidToMechanic(false);
        Service service5 = new Service();
        service5.setName("Tire Rotation");
        service5.setMechanic(mechanic3);
        service5.setPrice(new BigDecimal("55.25"));
        service5.setWasPaidToMechanic(false);
        Service service6 = new Service();
        service6.setName("Engine Tune-up");
        service6.setMechanic(mechanic4);
        service6.setPrice(new BigDecimal("120.00"));
        service6.setWasPaidToMechanic(false);
        Service service7 = new Service();
        service7.setName("Air Conditioning Service");
        service7.setMechanic(mechanic5);
        service7.setPrice(new BigDecimal("200.00"));
        service7.setWasPaidToMechanic(false);
        Service service8 = new Service();
        service8.setName("Radiator Flush");
        service8.setMechanic(mechanic6);
        service8.setPrice(new BigDecimal("85.75"));
        service8.setWasPaidToMechanic(false);
        Service service9 = new Service();
        service9.setName("Fuel Injection Service");
        service9.setMechanic(mechanic1);
        service9.setPrice(new BigDecimal("100.00"));
        service9.setWasPaidToMechanic(false);
        Service service10 = new Service();
        service10.setName("Wheel Alignment");
        service10.setMechanic(mechanic2);
        service10.setPrice(new BigDecimal("75.50"));
        service10.setWasPaidToMechanic(false);
        Service service11 = new Service();
        service11.setName("Battery Replacement");
        service11.setMechanic(mechanic3);
        service11.setPrice(new BigDecimal("55.25"));
        service11.setWasPaidToMechanic(false);
        Service service1 = new Service();
        service1.setName("Brake Pad Replacement");
        service1.setMechanic(mechanic4);
        service1.setPrice(new BigDecimal("120.00"));
        service1.setWasPaidToMechanic(false);

        List.of(service1, service2, service3, service4, service5, service6,
                        service7, service8, service9, service10, service11)
                .forEach(serviceService::add);

        Order order1 = new Order();
        order1.setCar(car1);
        order1.setDescription("Something wrong with engine");
        Order order2 = new Order();
        order2.setCar(car2);
        order2.setDescription("Need new brake pads");
        Order order3 = new Order();
        order3.setCar(car3);
        order3.setDescription("Replace damaged windshield");
        Order order4 = new Order();
        order4.setCar(car4);
        order4.setDescription("Oil change and tire rotation");
        Order order5 = new Order();
        order5.setCar(car1);
        order5.setDescription("Install new sound system");
        Order order6 = new Order();
        order6.setCar(car2);
        order6.setDescription("Replace brake pads");
        List.of(order1, order2, order3, order4, order5, order6).forEach(orderService::add);
        orderService.addProducts(1L, List.of(1L, 2L));
        orderService.addProducts(2L, List.of(3L, 4L));
        orderService.addProducts(3L, List.of(5L, 6L));
        orderService.addProducts(4L, List.of(7L, 8L));
        orderService.addProducts(5L, List.of(9L, 10L));
        orderService.addServices(1L, List.of(1L, 2L));
        orderService.addServices(2L, List.of(3L, 4L));
        orderService.addServices(3L, List.of(5L, 6L));
        orderService.addServices(4L, List.of(7L, 8L));
        orderService.addServices(5L, List.of(9L, 10L));
    }
}
